import { SlashCommandBuilder } from "discord.js";

export const commands = [
  new SlashCommandBuilder().setName("status").setDescription("Shows current session progress"),
  new SlashCommandBuilder().setName("start").setDescription("Starts run-sessions.js").addBooleanOption((o) => o.setName("reset").setDescription("Clear progress and restart from Session 1").setRequired(false)),
  new SlashCommandBuilder().setName("restart").setDescription("Restarts run-sessions.js — completed sessions skipped"),
  new SlashCommandBuilder().setName("stop").setDescription("Stops the running script and/or security fix"),
  new SlashCommandBuilder().setName("reset").setDescription("Clears progress and restarts from scratch").addStringOption((o) => o.setName("confirm").setDescription("Type 'yes' to confirm").setRequired(true)),
  new SlashCommandBuilder().setName("logs").setDescription("Shows the last lines of the current log file").addIntegerOption((o) => o.setName("lines").setDescription("Number of lines (default: 20, max: 50)").setRequired(false).setMinValue(5).setMaxValue(50)),
  new SlashCommandBuilder().setName("rate-limit").setDescription("Shows the estimated rate-limit status"),
  new SlashCommandBuilder().setName("security-status").setDescription("Shows all security findings from reports"),
  new SlashCommandBuilder().setName("start-resolve-security").setDescription("Starts Claude to fix all security violations"),
  new SlashCommandBuilder().setName("detect-sessions").setDescription("Analyzes all session files and shows prompt breakdown"),
  new SlashCommandBuilder().setName("setup").setDescription("Creates directories, CLAUDE.md and Session1.md template").addStringOption((o) => o.setName("plan").setDescription("Your Claude subscription plan").setRequired(false).addChoices({ name: "Pro ($20/mo)", value: "pro" }, { name: "Max 5× ($100/mo)", value: "max5" }, { name: "Max 20× ($200/mo)", value: "max20" })).addBooleanOption((o) => o.setName("override").setDescription("Embed override config in session template?").setRequired(false)),
  new SlashCommandBuilder().setName("new-session").setDescription("Creates a new session file from template").addIntegerOption((o) => o.setName("number").setDescription("Session number").setRequired(true).setMinValue(1).setMaxValue(20)).addBooleanOption((o) => o.setName("override").setDescription("Embed override config?").setRequired(false)),
  new SlashCommandBuilder().setName("settings").setDescription("View or change bot/runner settings").addSubcommand((s) => s.setName("show").setDescription("Show all current settings")).addSubcommand((s) => s.setName("set").setDescription("Change a setting").addStringOption((o) => o.setName("key").setDescription("Setting key to change").setRequired(true).addChoices(
    { name: "runner.defaultModel", value: "runner.defaultModel" },
    { name: "runner.maxTurns", value: "runner.maxTurns" },
    { name: "runner.pauseMinutes", value: "runner.pauseMinutes" },
    { name: "runner.claudePlan", value: "runner.claudePlan" },
    { name: "runner.skipPermissions", value: "runner.skipPermissions" },
    { name: "runner.parallel", value: "runner.parallel" },
    { name: "runner.autoSecurityFix", value: "runner.autoSecurityFix" },
    { name: "runner.archiveOnComplete", value: "runner.archiveOnComplete" },
    { name: "runner.workDir", value: "runner.workDir" },
    { name: "sessions.count", value: "sessions.count" },
    { name: "logging.keepLogs", value: "logging.keepLogs" },
    { name: "dashboard.port", value: "dashboard.port" },
    { name: "bot.channelId", value: "bot.channelId" },
    { name: "bot.webhookUrl", value: "bot.webhookUrl" },
    { name: "bot.locale", value: "bot.locale" },
  )).addStringOption((o) => o.setName("value").setDescription("New value").setRequired(true))).addSubcommand((s) => s.setName("reset").setDescription("Reset all settings to defaults")),
  new SlashCommandBuilder().setName("archive").setDescription("Manage run archives").addSubcommand((s) => s.setName("now").setDescription("Archive the current run immediately")).addSubcommand((s) => s.setName("list").setDescription("List all archived runs")).addSubcommand((s) => s.setName("prune").setDescription("Delete old archives (keep last N)").addIntegerOption((o) => o.setName("keep").setDescription("Number to keep (default: 5)").setRequired(false).setMinValue(1).setMaxValue(20))),
  new SlashCommandBuilder().setName("validate-sessions").setDescription("Validates all session files against the expected template structure"),
  new SlashCommandBuilder().setName("help").setDescription("Shows all available commands"),
  new SlashCommandBuilder().setName("info").setDescription("Shows version, system info, and changelog"),

  // New commands
  new SlashCommandBuilder().setName("set-timeout").setDescription("Set a per-session timeout override").addIntegerOption((o) => o.setName("session").setDescription("Session number").setRequired(true).setMinValue(1).setMaxValue(20)).addIntegerOption((o) => o.setName("minutes").setDescription("Timeout in minutes").setRequired(true).setMinValue(1).setMaxValue(600)),
  new SlashCommandBuilder().setName("pause").setDescription("Pause after the current session completes"),
  new SlashCommandBuilder().setName("resume").setDescription("Resume a paused run"),
  new SlashCommandBuilder().setName("retry").setDescription("Re-run a single failed/completed session").addIntegerOption((o) => o.setName("session").setDescription("Session number to retry").setRequired(true).setMinValue(1).setMaxValue(20)),
  new SlashCommandBuilder().setName("dry-run").setDescription("Validate sessions and estimate tokens without executing"),
  new SlashCommandBuilder().setName("schedule").setDescription("Schedule a run at a specific time").addStringOption((o) => o.setName("time").setDescription("Time in HH:MM (24h format)").setRequired(true)),
  new SlashCommandBuilder().setName("cancel-schedule").setDescription("Cancel a scheduled run"),
  new SlashCommandBuilder().setName("override").setDescription("Set a per-session model override").addIntegerOption((o) => o.setName("session").setDescription("Session number").setRequired(true).setMinValue(1).setMaxValue(20)).addStringOption((o) => o.setName("model").setDescription("Model name (e.g. claude-sonnet-4-5)").setRequired(true)),
  new SlashCommandBuilder().setName("diff").setDescription("Compare session output between last two archived runs").addIntegerOption((o) => o.setName("session").setDescription("Session number").setRequired(true).setMinValue(1).setMaxValue(20)),
  new SlashCommandBuilder().setName("export-logs").setDescription("Export all log files as a Discord attachment"),
  new SlashCommandBuilder().setName("git-changes").setDescription("Show files modified by Claude in the current run").addStringOption((o) => o.setName("file").setDescription("Specific file to show diff for").setRequired(false)),
  new SlashCommandBuilder().setName("dashboard").setDescription("Shows the web dashboard URL"),
  new SlashCommandBuilder().setName("watch").setDescription("Live-stream Claude output to Discord").addStringOption((o) => o.setName("action").setDescription("Start or stop watching").setRequired(false).addChoices({ name: "Start", value: "start" }, { name: "Stop", value: "stop" })),
  new SlashCommandBuilder().setName("dependency-graph").setDescription("Visualize session dependency relationships"),
  new SlashCommandBuilder().setName("setup-wizard").setDescription("Interactive setup — guides you through plan, model, and permissions"),

  // Phase 2 commands
  new SlashCommandBuilder().setName("create-session").setDescription("AI-generate a session file from a task description").addStringOption((o) => o.setName("task").setDescription("Task description for the session").setRequired(true)),
  new SlashCommandBuilder().setName("estimate").setDescription("Detailed cost/time estimate for the current sessions"),
  new SlashCommandBuilder().setName("health").setDescription("Comprehensive runtime health check"),
  new SlashCommandBuilder().setName("generate-template").setDescription("Scaffold a session or agent template").addStringOption((o) => o.setName("which").setDescription("Template type").setRequired(true).addChoices(
    { name: "Bug Fix (session)", value: "bugfix" },
    { name: "New Feature (session)", value: "feature" },
    { name: "Refactor (session)", value: "refactor" },
    { name: "Documentation (session)", value: "docs" },
    { name: "Migration (session)", value: "migration" },
    { name: "Security Audit (session)", value: "security-audit" },
    { name: "Fullstack Agent", value: "fullstack" },
    { name: "Database Agent", value: "database" },
    { name: "Security Agent", value: "security" },
    { name: "Manager Agent", value: "manager" },
  )),
  new SlashCommandBuilder().setName("rollback").setDescription("Revert files changed by a session via git").addIntegerOption((o) => o.setName("session").setDescription("Session number to rollback").setRequired(true).setMinValue(1).setMaxValue(20)),
  new SlashCommandBuilder().setName("compare-sessions").setDescription("Cross-archive comparison for a session").addIntegerOption((o) => o.setName("session").setDescription("Session number to compare").setRequired(true).setMinValue(1).setMaxValue(20)).addStringOption((o) => o.setName("archive").setDescription("Specific archive name to compare against").setRequired(false)),
  new SlashCommandBuilder().setName("retry-prompt").setDescription("Re-run a specific prompt from a session").addIntegerOption((o) => o.setName("session").setDescription("Session number").setRequired(true).setMinValue(1).setMaxValue(20)).addIntegerOption((o) => o.setName("prompt").setDescription("Prompt number").setRequired(true).setMinValue(1).setMaxValue(20)),
].map((c) => c.toJSON());
